site_name: IHC - Neoenergia
site_description: "Repositório do grupo 03 de IHC"
repo_name: '2024.2-Neoenergia'
repo_url: 'https://github.com/Interacao-Humano-Computador/2024.2-Neoenergia'

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - admonition

plugins:
  - glightbox

nav:
  - Início: index.md
  
  - Apresentações:
    - Apresentação 01: apresentações/apresentacao01.md
    - Apresentação 02: apresentações/apresentacao02.md
    - Apresentação 03: apresentações/apresentacao03.md
    - Apresentação 04: apresentações/apresentacao04.md
    - Apresentação 05: apresentações/apresentacao05.md
    - Apresentação 06: apresentações/apresentacao06.md
    - Apresentação 07: apresentações/apresentacao07.md
  
  - Atas: 
    - Ata 01: atas/ata01.md
    - Ata 02: atas/ata02.md
    - Ata 03: atas/ata03.md
    - Ata 04: atas/ata04.md
    - Ata 05: atas/ata05.md
  
  - Planejamento: 
    - Cronograma: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Heatmap: planejamento/heatmap.md
    - Sites Avaliados: planejamento/sites-avaliados.md
    - Site Escolhido: planejamento/site-escolhido.md
    - Processo de Design: planejamento/processo-design.md

  - Análise de Requisitos:
    - ‎:
      - Aspectos Éticos: analise-requisitos/aspectos-eticos.md
      - Perfil de Usuário: analise-requisitos/perfil-usuario.md
      - Cenários: analise-requisitos/cenarios.md
      - Personas: analise-requisitos/personas.md
      - Análise de Tarefas:
        - GOMS: analise-requisitos/goms.md
        - HTA: analise-requisitos/hta.md
      - Metas de Usabilidade: analise-requisitos/metas-usabilidade.md
      - Príncipios Gerais: analise-requisitos/principios-gerais.md
      - Guia de Estilo: analise-requisitos/guia-estilo.md
      - Características Gerais: analise-requisitos/caracteristicas-gerais.md

  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
      - Análise de Tarefas:
        - Planejamento da Avaliação: design-avaliação-desenvolvimento/planej-avaliacao-analise.md
        - Planejamento do Relato dos Resultados: design-avaliação-desenvolvimento/planej-relato-analise.md
        - Relato dos Resultados: design-avaliação-desenvolvimento/relato-analise.md
      - Storyboard: 
        - Planejamento da Avaliação: design-avaliação-desenvolvimento/planej-avaliacao-storyboard.md
        - Planejamento do Relato dos Resultados: design-avaliação-desenvolvimento/planej-relato-storyboard.md
        - Relato dos Resultados: design-avaliação-desenvolvimento/relato-storyboard.md
        - Storyboards: design-avaliação-desenvolvimento/storyboards.md
    - Nível 2:
      - Protótipo de Papel:
        - Planejamento da Avaliação: design-avaliação-desenvolvimento/planej-avaliacao-prototipo-papel.md
        - Planejamento do Relato dos Resultados: design-avaliação-desenvolvimento/planej-relato-prototipo-papel.md
        - Relato dos Resultados: design-avaliação-desenvolvimento/relato-prototipo-papel.md
        - Protótipos de Papel: design-avaliação-desenvolvimento/prototipos-papel.md
    - Nível 3:
      - Protótipo de Alta Fidelidade:
        - Planejamento da Avaliação: design-avaliação-desenvolvimento/planej-avaliacao-prototipo-alta.md
        - Planejamento do Relato dos Resultados: design-avaliação-desenvolvimento/planej-relato-prototipo-alta.md
        - Relato dos Resultados: design-avaliação-desenvolvimento/relato-prototipo-alta.md
        - Protótipos de Alta Fidelidade: design-avaliação-desenvolvimento/prototipos-alta.md

  - Verificação:
    - Nosso grupo:
      - Etapa 01:
        - Planejamento da Verificação da Etapa 1: verificação/grupo/etapa1/planejamento-verificacao.md
        - Cronograma: verificacao/grupo/etapa1/verificacao-cronogrma.md
        - Ferramentas: verificacao/grupo/etapa1/verificacao-ferramentas.md
        - Processo de Design: verificacao/grupo/etapa1/verificacao-processo-design.md
        - Site Escolhido: verificacao/grupo/etapa1/verificacao-site-escolhido.md
      - Etapa 02: verificação/verificacao-02.md
      - Etapa 03: verificação/verificacao-03.md
      - Etapa 04: verificação/verificacao-04.md
      - Etapa 05: verificação/verificacao-05.md
      - Etapa 06: verificação/verificacao-06.md
      - Etapa 07: verificação/verificacao-07.md
    - Grupo 04:
      - Verificação 01: verificação/verificacaog4-01.md
      - Verificação 02: verificação/verificacaog4-02.md
      - Verificação 03: verificação/verificacaog4-03.md
      - Verificação 04: verificação/verificacaog4-04.md
      - Verificação 05: verificação/verificacaog4-05.md
      - Verificação 06: verificação/verificacaog4-06.md
      - Verificação 07: verificação/verificacaog4-07.md

theme:
  icon:
    admonition:
      note: octicons/info-16
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - contention.code.copy
  language: pt-BR
  favicon: assets/neoenergia.png
  logo: assets/neoenergia.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Modo escuro
      primary: green
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Modo claro
      primary: green
      accent: amber

extra:
  version:
    provider: mike

extra_css: [stylesheets/extra.css]
  
